[package]
name = "airdispatch-crypto"
version = "0.1.0"
authors = ["Wil Thomason <wil.thomason@gmail.com>", "Hunter Leath <h@hunterleath.com>"]

[dependencies]
openssl     = "^0.7.6"
log         = "^0.3.5"
secp256k1   = "^0.5.4"
rust-crypto = "^0.2.34"
